apiVersion: batch/v1
kind: Job
metadata:
  name: nexus-setup
  labels:
    app: nexus-setup
spec:
  template:
    metadata:
      name: nexus-setup-job
    spec:
      restartPolicy: OnFailure
      serviceAccountName: nexus-setup
      volumes:
      - configMap:
          defaultMode: 420
          name: nexussetup
        name: nexussetup
      containers:
      - name: nc
        image: quay.io/openshift/origin-jenkins-agent-base:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "source /tmp/config-nexus.sh"
        volumeMounts:
        - mountPath: /tmp/config-nexus.sh
          name: nexussetup
          subPath: config-nexus.sh
