kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-sonatype-nexus-data
  labels:
    app: sonatype-nexus
    fullname: nexus-sonatype-nexus
    chart: sonatype-nexus-1.1.8
    release: nexus
    heritage: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
